services:
  postgres:
    image: postgres:16-alpine
    container_name: norse-mythos-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: norse_mythos
      POSTGRES_USER: norse_user
      POSTGRES_PASSWORD: norse_local_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
